# Generated by Django 6.0.1 on 2026-02-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('second_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='presentationscategory',
            name='video',
        ),
        migrations.AddField(
            model_name='presentationscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='assignmentscategory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='listeningcategory',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='listening/'),
        ),
        migrations.AlterField(
            model_name='listeningcategory',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignmentscategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.author'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.author'),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.author'),
        ),
        migrations.AlterField(
            model_name='listeningcategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.author'),
        ),
        migrations.AlterField(
            model_name='presentationscategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.author'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='english.question')),
            ],
        ),
    ]
