# Generated by Django 6.0.1 on 2026-02-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_author_question_remove_presentationscategory_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentscategory',
            old_name='video',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='casestudycategory',
            old_name='video',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='independentworkcategory',
            old_name='video',
            new_name='file',
        ),
    ]
