# Generated by Django 6.0.1 on 2026-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='presentationscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
