# Generated by Django 6.0.1 on 2026-02-21 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscategory',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presentationscategory',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
