# Generated by Django 6.0.1 on 2026-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_alter_assignmentscategory_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='listeningcategory',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='listening/'),
        ),
        migrations.AlterField(
            model_name='presentationscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
