# Generated by Django 6.0.1 on 2026-03-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_alter_assignmentscategory_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='independentworkcategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='listeningcategory',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='listening/'),
        ),
        migrations.AlterField(
            model_name='presentationscategory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
